###
GET http://localhost:3000/api/roles
Content-Type: application/json

###
GET http://localhost:3000/api/role/2
Content-Type: application/json

###
POST http://localhost:3000/api/role
Content-Type: application/json

{
    "name":"role_name2"
}


###
PATCH http://localhost:3000/api/role/1
Content-Type: application/json

{
    "name":"name222222222222222"
}

###
DELETE http://localhost:3000/api/role/3
Content-Type: application/json